# Generated by Django 4.2.7 on 2023-12-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_alter_crawleddata_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawledData',
        ),
    ]
